# Generated by Django 4.2 on 2023-06-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_consignment_photo'),
        ('drivers', '0003_alter_truck_image'),
        ('waybill', '0002_waybill_track_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_driver', to='drivers.drivermore'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_sender', to='customer.customermore'),
        ),
    ]
