# Generated by Django 4.2 on 2023-06-15 16:03

from django.db import migrations, models
import drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_drivermore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(upload_to=drivers.models.Truck.upload_to, verbose_name='image'),
        ),
    ]
