# Generated by Django 4.2 on 2023-06-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_truck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='drivers.drivermore'),
        ),
        migrations.AlterField(
            model_name='karthoshmand',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karthoshmand', to='drivers.drivermore'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='drivers.drivermore'),
        ),
    ]
