# Generated by Django 4.2 on 2023-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_comment_user_alter_post_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ImageField(upload_to='attachment', verbose_name='attachment'),
        ),
    ]
