# Generated by Django 3.2 on 2022-01-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='create on')),
                ('more', models.JSONField(blank=True, null=True, verbose_name='more')),
                ('consignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_consignment', to='customer.consignment')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_driver', to='account.driveruser')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_sender', to='account.customeruser')),
            ],
        ),
    ]
