# Generated by Django 3.2 on 2021-11-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='create on')),
                ('more', models.JSONField(verbose_name='more')),
                ('consignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='customer.consignment')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='drivers.drivermore')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='customer.customermore')),
            ],
        ),
    ]
