# Generated by Django 3.2 on 2022-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='created_on',
            field=models.DateTimeField(auto_created=True, verbose_name='create on'),
        ),
    ]
