# Generated by Django 4.0.4 on 2023-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='track_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='track_code'),
        ),
    ]
