# Generated by Django 4.0.4 on 2022-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0002_alter_waybill_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='create on'),
        ),
    ]
