# Generated by Django 3.2 on 2022-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to='Certificate', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='karthoshmand',
            name='image',
            field=models.ImageField(null=True, upload_to='kart_hoshmand', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(upload_to='truck', verbose_name='image'),
        ),
    ]
