# Generated by Django 3.2 on 2022-01-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20220107_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermore',
            name='Driver_licence',
        ),
        migrations.RemoveField(
            model_name='drivermore',
            name='kart_hoshmand',
        ),
        migrations.RemoveField(
            model_name='drivermore',
            name='truck',
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karthoshmand',
            name='user',
            field=models.OneToOneField(default=2009, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='user',
            field=models.OneToOneField(default=2009, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_time',
            field=models.DateField(verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='validity_date',
            field=models.DateField(verbose_name='validity date'),
        ),
        migrations.AlterField(
            model_name='drivermore',
            name='Date_of_birth',
            field=models.DateField(null=True, verbose_name='birth'),
        ),
    ]
