# Generated by Django 3.2 on 2022-01-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('drivers', '0003_auto_20220108_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='D_user', to='account.driveruser'),
        ),
    ]
