# Generated by Django 3.2 on 2022-01-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_drivermore_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivermore',
            options={'verbose_name': 'DriverMore', 'verbose_name_plural': 'DriversMore'},
        ),
    ]
